version: '3'

services:
  db:
    image: postgres:13.8
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: sample
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: 5dm7BZnATbgW77dT
